### ISSUE TITLE
新的脚本提示错误

### ISSUE THREAD

**Issue by wangluyichen** [kuoruan/shell-scripts#11]
./kcptun.sh: line 7: syntax error near unexpected token `newline'
./kcptun.sh: line 7: `<!DOCTYPE html>'

**Comment by kuoruan** [comment]
或许是你的脚本没下载下来？

**Comment by wangluyichen** [comment]
@kuoruan 下载成功的啊

**Comment by wangluyichen** [comment]
地址两个：
wget --no-check-certificate https://github.com/kuoruan/shell-scripts/blob/master/kcptun/kcptun.sh
wget --no-check-certificate https://github.com/kuoruan/shell-scripts/raw/master/kcptun/kcptun.sh
下面那个正常，上面的报错 @kuoruan

**Comment by kuoruan** [comment]
上面那个是网页
下面那个才是脚本

**Comment by wangluyichen** [comment]
@kuoruan 看起来文件名都是一样的嘛。。
