### ISSUE TITLE
可否添加ipv6支持？

### ISSUE THREAD

**Issue by chestnutprog** [kuoruan/shell-scripts#12]

**Comment by kuoruan** [comment]
ipv6 本就支持的，连的时候填写 ipv6 地址即可

**Comment by chestnutprog** [comment]
ipv6需要改配置的吧。。。

**Comment by chestnutprog** [comment]
支持ipv6的话ip6tables里应该有东西？

**Comment by 1265578519** [comment]
路过帮顶

**Comment by kuoruan** [comment]
ipv6 的防火墙规则可以自己添加，现在一般高版本的 linux 都是自带的 firewalld

**Comment by chestnutprog** [comment]
自己尝试加不上
ip6tables v1.4.21: can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
