### ISSUE TITLE
安装后获取不到网站源IP

### ISSUE THREAD

**Issue by 1265578519** [kuoruan/shell-scripts#13]
![image](https://user-images.githubusercontent.com/6442439/36721773-daa50cdc-1be6-11e8-9019-2b791bf3f0f6.png)
大佬说改成这样。。怎么改

**Comment by kuoruan** [comment]
没明白你的问题

**Comment by 1265578519** [comment]
![image](https://user-images.githubusercontent.com/6442439/36721998-6303b7d6-1be7-11e8-88cd-94df7a6c6998.png)
，，就是服务器获取不到IP了

**Comment by kuoruan** [comment]
ip addr
ifconfig
？

**Comment by 1265578519** [comment]
![image](https://user-images.githubusercontent.com/6442439/36722536-bebe01de-1be8-11e8-8f17-aac56ef23075.png)

**Comment by kuoruan** [comment]
你的 IP 不是 91.121.255.214 吗？

**Comment by 1265578519** [comment]
是啊，获取到的IP全是10.0.0.2
![image](https://user-images.githubusercontent.com/6442439/36723339-edb58a28-1bea-11e8-9782-bbaa8d0cbbc8.png)

**Comment by kuoruan** [comment]
对啊，你的数据被 lkl 接管了，通过 10.0.0.1 转发的，当然就是 10.0.0.2 了
我不知道你的目的是什么，如果你无法达到你的需求，就只有卸载 lkl 了
