### ISSUE TITLE
未找到已安装的 easy_install 命令

### ISSUE THREAD

**Issue by ggggxiaolong** [kuoruan/shell-scripts#14]
```shell
未找到已安装的 easy_install 命令，
请先手动安装 python-setuptools
然后重新运行安装脚本
```
ubuntu 18.04 
已经安装 python-setuptools 但是脚本报错

**Comment by kuoruan** [comment]
没在这么新的环境上测试过，不排除有 BUG

**Comment by ye4241** [comment]
改脚本逻辑为使用pip安装supervisor就好了

**Comment by genkin-he** [comment]
@ye4241 我也遇到这个问题了，请问该怎么改啊？

**Comment by jiangzc** [comment]
According to the [changelog](https://launchpad.net/ubuntu/+source/python-setuptools/39.0.1-2) easy_install was removed from the python-setuptools package.

解决方法：
1. 卸载最新版python-setuptools
   `sudo apt remove python-setuptools`
2. 安装python-setuptools  38.60版  
[历史版本](https://pypi.org/project/setuptools/#history)
