### ISSUE TITLE
这是怎么回事?

### ISSUE THREAD

**Issue by wyfang** [kuoruan/shell-scripts#15]
[root@wyfang ~]# wget https://raw.githubusercontent.com/kuoruan/kcptun_installer/master/kcptun.sh
-bash: wget https://raw.githubusercontent.com/kuoruan/kcptun_installer/master/kcptun.sh: No such file or directory

**Comment by kuoruan** [comment]
没装 wget 吗？试试 curl

Player <notifications@github.com> 于2018年8月17日周五 下午10:37写道：

**Comment by wyfang** [comment]
可以
