### ISSUE TITLE
Kcptun不能正常启动Server端端口

### ISSUE THREAD

**Issue by 84795949** [kuoruan/shell-scripts#17]
我在阿里云Centos6.8的ECS上与AWS的Ubuntu16.04上分别做了测试，clone脚本后，一路默认配置回车，最后显示安装完毕，启动成功，但是实际上没有开放端口，见图：
![2018-08-22 10-59-04](https://user-images.githubusercontent.com/21697438/44440412-88c7c280-a5fa-11e8-8a2c-16e1c687155f.png)
![2](https://user-images.githubusercontent.com/21697438/44440447-b3198000-a5fa-11e8-92ae-b153ac08974b.png)

**Comment by cokeisnotbest** [comment]
这种ECS要去平台的控制端通过云提供的界面开启对应的端口吧。

**Comment by 84795949** [comment]
@cokeisnotbest 刚发现开的不是tcp端口好像，只有一个udp ipv6的端口开开了，不是去云提供的界面，我说的不是一回事，那是防火墙层面，而我说的是 在服务端，这个端口压根就没打开，但是直到刚才我连上了，这个端口都没显示正常开放，我对网络协议不是很懂，能用就行拉 哈哈
