### ISSUE TITLE
安装依赖失败

### ISSUE THREAD

**Issue by dackdawn** [kuoruan/shell-scripts#26]
yum -y -q install python-pip
失败，找不到这个包

要先安装epel-release

解决方法：
先安装epel-release:
yum -y install epel-release

**Comment by kuoruan** [comment]
你是 CentOS 几？

**Comment by dackdawn** [comment]
> 你是 CentOS 几？

centos 7.6

**Comment by kuoruan** [comment]
```
wget -qO- https://bootstrap.pypa.io/get-pip.py | python
```

这样装 pip 试试
