### ISSUE TITLE
新版本安装错误

### ISSUE THREAD

**Issue by dengerwa** [kuoruan/shell-scripts#27]
centos 6.4 mini   安装报错 pip版本过低 然后升级pip过后 直接提示Python环境已经被破坏     去年安装的时候都没问题 希望指导一下

**Comment by kuoruan** [comment]
报错信息是 pip 版本过低吗？

**Comment by kuoruan** [comment]
再试试新脚本

**Comment by dengerwa** [comment]
SyntaxError: invalid syntax
未找到已安装的 pip 命令，请先手动安装 python-pip
本脚本自 v21 版开始使用 pip 来安装 Supervisior。

1. 对于 Debian 系的 Linux 系统，可以尝试使用：
  sudo apt-get install -y python-pip 来进行安装

2. 对于 Redhat 系的 Linux 系统，可以尝试使用：
  sudo yum install -y python-pip 来进行安装
  * 注：如果提示未找到该软件，请先使用以下命令来安装扩展软件仓库：
    sudo yum install -y epel-release

3. 如果以上方法都失败了，请使用以下命令来手动安装：
  wget -qO- --no-check-certificate https://bootstrap.pypa.io/get-pip.py | python

pip 安装完毕之后，请重新运行安装脚本。

**Comment by kuoruan** [comment]
把上面的日志一块儿贴出来

**Comment by dengerwa** [comment]
[root@localhost ~]# yum install -y python-pip
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Error: Cannot retrieve metalink for repository: epel. Please verify its path and try again
[root@localhost ~]# yum install -y epel-release
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Error: Cannot retrieve metalink for repository: epel. Please verify its path and try again
[root@localhost ~]# wget -qO- --no-check-certificate https://bootstrap.pypa.io/get-pip.py | python
Traceback (most recent call last):
  File "<stdin>", line 21373, in <module>
  File "<stdin>", line 197, in main
  File "<stdin>", line 82, in bootstrap
  File "/tmp/tmpu7msgn/pip.zip/pip/_internal/__init__.py", line 19, in <module>
  File "/tmp/tmpu7msgn/pip.zip/pip/_vendor/urllib3/__init__.py", line 8, in <module>
  File "/tmp/tmpu7msgn/pip.zip/pip/_vendor/urllib3/connectionpool.py", line 92
    _blocking_errnos = {errno.EAGAIN, errno.EWOULDBLOCK}
                                    ^
SyntaxError: invalid syntax
[root@localhost ~]#

**Comment by dengerwa** [comment]
2019-01-25 14:42:29 (5.24 MB/s) - 已保存 “kcptun-v20190109.tar.gz” [4884590/4884590])

+ sha1sum -c
+ echo '1cb077f0ca3872b5c641d7780f133225dfa77c0d  kcptun-v20190109.tar.gz'
kcptun-v20190109.tar.gz: 确定
+ mkdir -p /var/log/kcptun
+ chmod a+w /var/log/kcptun
+ tar -zxf kcptun-v20190109.tar.gz -C /usr/local/kcptun
+ sleep 3
+ python
+ wget -qO- --no-check-certificate https://bootstrap.pypa.io/get-pip.py
Traceback (most recent call last):
  File "<stdin>", line 21373, in <module>
  File "<stdin>", line 197, in main
  File "<stdin>", line 82, in bootstrap
  File "/tmp/tmpdS2XVg/pip.zip/pip/_internal/__init__.py", line 19, in <module>
  File "/tmp/tmpdS2XVg/pip.zip/pip/_vendor/urllib3/__init__.py", line 8, in <module>
  File "/tmp/tmpdS2XVg/pip.zip/pip/_vendor/urllib3/connectionpool.py", line 92
    _blocking_errnos = {errno.EAGAIN, errno.EWOULDBLOCK}
                                    ^
SyntaxError: invalid syntax
未找到已安装的 pip 命令，请先手动安装 python-pip
本脚本自 v21 版开始使用 pip 来安装 Supervisior。

1. 对于 Debian 系的 Linux 系统，可以尝试使用：
  sudo apt-get install -y python-pip 来进行安装

2. 对于 Redhat 系的 Linux 系统，可以尝试使用：
  sudo yum install -y python-pip 来进行安装
  * 注：如果提示未找到该软件，请先使用以下命令来安装扩展软件仓库：
    sudo yum install -y epel-release

3. 如果以上方法都失败了，请使用以下命令来手动安装：
  wget -qO- --no-check-certificate https://bootstrap.pypa.io/get-pip.py | python

pip 安装完毕之后，请重新运行安装脚本。
[root@localhost ~]# SyntaxError: invalid syntax
未找到已安装的 pip 命令，请先手动安装 python-pip
本脚本自 v21 版开始使用 pip 来安装 Supervisior。

1. 对于 Debian 系的 Linux 系统，可以尝试使用：
  sudo apt-get install -y python-pip 来进行安装

2. 对于 Redhat 系的 Linux 系统，可以尝试使用：
  sudo yum install -y python-pip 来进行安装
  * 注：如果提示未找到该软件，请先使用以下命令来安装扩展软件仓库：
    sudo yum install -y epel-release

3. 如果以上方法都失败了，请使用以下命令来手动安装：
  wget -qO- --no-check-certificate https://bootstrap.pypa.io/get-pip.py | python

pip 安装完毕之后，请重新运行安装脚本。

**Comment by kuoruan** [comment]
```
python --version
```

**Comment by dengerwa** [comment]
[root@localhost ~]# python --version
Python 2.6.6
[root@localhost ~]#

**Comment by kuoruan** [comment]
看看 pip 的版本
```
pip --version
```

用 ```wget -qO- --no-check-certificate https://bootstrap.pypa.io/get-pip.py | python``` 一般就能正常安装 pip 了，而且你的 yum 的 epel 仓库有问题，找找原因

**Comment by dengerwa** [comment]
[root@localhost ~]# pip --version
-bash: pip: command not found
[root@localhost ~]# wget -qO- --no-check-certificate https://bootstrap.pypa.io/get-pip.py | python
Traceback (most recent call last):
  File "<stdin>", line 21373, in <module>
  File "<stdin>", line 197, in main
  File "<stdin>", line 82, in bootstrap
  File "/tmp/tmpiiELGe/pip.zip/pip/_internal/__init__.py", line 19, in <module>
  File "/tmp/tmpiiELGe/pip.zip/pip/_vendor/urllib3/__init__.py", line 8, in <module>
  File "/tmp/tmpiiELGe/pip.zip/pip/_vendor/urllib3/connectionpool.py", line 92
    _blocking_errnos = {errno.EAGAIN, errno.EWOULDBLOCK}
                                    ^
SyntaxError: invalid syntax
[root@localhost ~]#

**Comment by williamxch** [comment]
[root@host ~]# pip --version
-bash: pip: command not found
我和上面那老哥出现的状况一样。。
之前安装kcp都是木有问题的
是WIN10的问题吗？
能不能回退KCP版本。。

**Comment by dengerwa** [comment]
[epel]
name=Extra Packages for Enterprise Linux 6 - $basearch
baseurl=http://download.fedoraproject.org/pub/epel/6/$basearch
#mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
源我已经修改回来了

**Comment by kuoruan** [comment]
等等，我找个 CentOS 6 的环境

**Comment by dengerwa** [comment]
我的是centos 6.4 mini 精简版

**Comment by williamxch** [comment]
我是Centos 6 x86_64 bbr

**Comment by kuoruan** [comment]
稍等一下，由于新版脚本使用 pip 来安装 supervisor 了，在低版本的 python 上安装可能有些问题

**Comment by dengerwa** [comment]
OK 等你喲

**Comment by williamxch** [comment]
大佬辛苦了

**Comment by kuoruan** [comment]
行了

```
./kcptun update
```

然后再次安装

**Comment by dengerwa** [comment]
好的马上测试

**Comment by dengerwa** [comment]
2019-01-25 16:33:27 (6.01 MB/s) - 已保存 “kcptun-v20190109.tar.gz” [4884590/4884590])

+ sha1sum -c
+ echo '1cb077f0ca3872b5c641d7780f133225dfa77c0d  kcptun-v20190109.tar.gz'
kcptun-v20190109.tar.gz: 确定
+ tar -zxf kcptun-v20190109.tar.gz -C /usr/local/kcptun
+ sleep 3
+ pip install --upgrade pip
You are using pip version 7.1.0, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Collecting pip
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading https://files.pythonhosted.org/packages/46/dc/7fd5df840efb3e56c8b4f768793a237ec4ee59891959d6a215d63f727023/pip-19.0.1-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 123kB/s
Installing collected packages: pip
  Found existing installation: pip 7.1.0
    Uninstalling pip-7.1.0:
      Successfully uninstalled pip-7.1.0
Successfully installed pip-19.0.1
+ pip install supervisor
Traceback (most recent call last):
  File "/usr/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/usr/lib/python2.6/site-packages/pip/_internal/__init__.py", line 19, in <module>
    from pip._vendor.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python2.6/site-packages/pip/_vendor/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python2.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 92
    _blocking_errnos = {errno.EAGAIN, errno.EWOULDBLOCK}
                                    ^
SyntaxError: invalid syntax
错误: 安装 Supervisor 失败，
请尝试使用
  pip install supervisor
来手动安装。

**Comment by kuoruan** [comment]
@dengerwa 分别执行：
```
python --version
pip --version
```

**Comment by dengerwa** [comment]
[root@localhost ~]# python --version
Python 2.6.6
[root@localhost ~]# pip --version
Traceback (most recent call last):
  File "/usr/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/usr/lib/python2.6/site-packages/pip/_internal/__init__.py", line 19, in <module>
    from pip._vendor.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python2.6/site-packages/pip/_vendor/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python2.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 92
    _blocking_errnos = {errno.EAGAIN, errno.EWOULDBLOCK}
                                    ^
SyntaxError: invalid syntax
[root@localhost ~]#

**Comment by kuoruan** [comment]
你动过你的 python 环境吗？
```
wget -qO- --no-check-certificate https://bootstrap.pypa.io/2.6/get-pip.py | python
```
用这个命令重新装一下 pip

**Comment by dengerwa** [comment]
我升级一下Python试试看

**Comment by dengerwa** [comment]
我按照https://www.cnblogs.com/harrymore/p/9024287.html 这个升级了 Python  然后pip install --upgrade pip 就成功了

**Comment by dengerwa** [comment]
非常感谢
