### ISSUE TITLE
更新了之后又出了新问题

### ISSUE THREAD

**Issue by williamxch** [kuoruan/shell-scripts#28]
2019-01-25 03:30:35 (9.27 MB/s) - “kcptun-v20190109.tar.gz” saved [4884590/4884590]

+ sha1sum -c
+ echo '1cb077f0ca3872b5c641d7780f133225dfa77c0d  kcptun-v20190109.tar.gz'
kcptun-v20190109.tar.gz: OK
+ tar -zxf kcptun-v20190109.tar.gz -C /usr/local/kcptun
+ sleep 3
+ pip install --upgrade pip
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Requirement already up-to-date: pip in /usr/lib/python2.6/site-packages
You are using pip version 9.0.3, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
+ pip install supervisor
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Requirement already satisfied: supervisor in /usr/lib/python2.6/site-packages
Requirement already satisfied: meld3>=0.6.5 in /usr/lib/python2.6/site-packages (from supervisor)
You are using pip version 9.0.3, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
+ echo_supervisord_conf
创建 Supervisor 配置文件失败!

求大佬解答下。。。

**Comment by kuoruan** [comment]
你手动执行一下：
```
echo_supervisord_conf
```
看看有输出吗

**Comment by williamxch** [comment]
[root@host ~]# python --version
Python 2.6.6
[root@host ~]# pip --version
pip 9.0.3 from /usr/lib/python2.6/site-packages (python 2.6)
[root@host ~]# echo_supervisord_conf
Traceback (most recent call last):
  File "/usr/bin/echo_supervisord_conf", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: meld3>=0.6.5

**Comment by kuoruan** [comment]
```
pip install --upgrade setuptools
```
然后再重新运行脚本

**Comment by williamxch** [comment]
已解决并捐助，感谢大佬~~

**Comment by kuoruan** [comment]
OK, Issue 关闭了
