### ISSUE TITLE
为什么windows10客户端，加速无效？

### ISSUE THREAD

**Issue by EdwardSituwende** [kuoruan/shell-scripts#3]
你好，我想问一下，为什么我在windows10客户端连上服务器之后，服务器日志一直显示stream closed，过了几秒就broken pipe了？
但是我在Android客户端使用，则一切正常。有什么解决办法吗？

**Comment by kuoruan** [comment]
同一实例不能多个客户端同时连。另外，看看两端的版本是否一致
