### ISSUE TITLE
无法连接的问题

### ISSUE THREAD

**Issue by huanglins** [kuoruan/shell-scripts#33]
搬瓦工通过 https://teddysun.com/486.html 这个安装的 ss，然后再安装的该 kcptun 。
我的 ss 端口是 5555，kcptun 端口是 55555，ip 127.0.0.1 其他都是默认配置
。kcptun 两端版本都是最新的。
客户端使用的是 mac ShadowsocksX-NG 1.8.2 填入配置后，客户端有正常的日志输出

```
2019/03/13 20:57:19 stream opened
2019/03/13 20:57:19 stream opened
2019/03/13 20:57:19 stream opened
2019/03/13 20:57:19 stream opened
2019/03/13 20:57:19 stream closed
2019/03/13 20:57:19 stream closed
```
这种，但是服务器这边没有任何日志输出，请问下这种会是什么情况？

**Comment by huanglins** [comment]
查看端口是：
[root@host kcptun]# ss -nl | grep 5555
udp    UNCONN     0      0         *:5555                  *:*                      
udp    UNCONN     0      0        :::55555                :::*                      
tcp    LISTEN     0      128       *:5555                  *:*

**Comment by kuoruan** [comment]
服务端的日志贴上来看看？

**Comment by huanglins** [comment]
<img width="684" alt="屏幕快照 2019-03-13 下午9 17 45" src="https://user-images.githubusercontent.com/10528244/54281828-8bf5c080-45d5-11e9-9151-8cb4587f1c10.png">

**Comment by kuoruan** [comment]
第一，看看你的 SS 服务端配置文件监听的地址是什么，
然后，贴一下本地的配置文件和 SS 的配置截图

**Comment by huanglins** [comment]
<img width="340" alt="屏幕快照 2019-03-13 下午9 20 24" src="https://user-images.githubusercontent.com/10528244/54282052-14746100-45d6-11e9-9a64-5f9774d0c343.png">
这是本地 ss 配置，但是ip地址我用了域名解析，不知道这是否有影响。ss 服务器端监听的地址是：0.0.0.0

**Comment by kuoruan** [comment]
你把配置里的端口改为 55555 呢？

**Comment by huanglins** [comment]
天呐，确实可以了，谢谢！！！
