### ISSUE TITLE
可不可以支持多IP

### ISSUE THREAD

**Issue by shap2zj** [kuoruan/shell-scripts#34]
服务器一个网卡给了4个IP号。。安装加速工具默认用的是主IP，不知道有没有方法可以换成其他IP？

**Comment by kuoruan** [comment]
可以使用命令：
```
./kcptun.sh reconfig
```
来重新配置

**Comment by shap2zj** [comment]
配置里好像只显示了target的IP，应该是SS的，改了之后出口IP倒是变了。。但是。。连接KCP服务器的地址还是主IP。请问有木有指令可以像SS那样改一下"server"的IP？亲

**Comment by kuoruan** [comment]
kcptun 默认就没有显式设置监听IP，监听的就是所有网卡，你直接用其他IP连也是可以的。
如果你想显式的指定IP，选择手动修改配置文件，在 ```listen``` 部分加上即可

**Comment by shap2zj** [comment]
哦。可以了呢！感谢！ T.T~

**Comment by shap2zj** [comment]
哦。可以了呢！感谢！ T.T~
