### ISSUE TITLE
服务启动失败

### ISSUE THREAD

**Issue by tomuGo** [kuoruan/shell-scripts#35]
virmach的机器
+ ip tuntap del dev lkl-tap-test mode tap
+ ip tuntap add dev lkl-tap-test mode tap
+ mkdir -p /usr/local/haproxy-lkl/etc /usr/local/haproxy-lkl/lib64 /usr/local/haproxy-lkl/sbin
+ useradd -U -s /usr/sbin/nologin -d /nonexistent haproxy
+ wget -O /usr/local/haproxy-lkl/sbin/haproxy --no-check-certificate https://github.com/kuoruan/shell-scripts/raw/master/ovz-bbr/bin/haproxy.linux2628_x86_64
--2019-03-23 02:20:52--  https://github.com/kuoruan/shell-scripts/raw/master/ovz-bbr/bin/haproxy.linux2628_x86_64
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/kuoruan/shell-scripts/master/ovz-bbr/bin/haproxy.linux2628_x86_64 [following]
--2019-03-23 02:20:52--  https://raw.githubusercontent.com/kuoruan/shell-scripts/master/ovz-bbr/bin/haproxy.linux2628_x86_64
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5106664 (4.9M) [application/octet-stream]
Saving to: '/usr/local/haproxy-lkl/sbin/haproxy'

/usr/local/haproxy-lk 100%[=========================>]   4.87M  --.-KB/s    in 0.05s   

2019-03-23 02:20:53 (90.5 MB/s) - '/usr/local/haproxy-lkl/sbin/haproxy' saved [5106664/5106664]

+ wget -O /usr/local/haproxy-lkl/sbin/haproxy-lkl --no-check-certificate https://github.com/kuoruan/shell-scripts/raw/master/ovz-bbr/bin/haproxy-lkl.sh
--2019-03-23 02:20:53--  https://github.com/kuoruan/shell-scripts/raw/master/ovz-bbr/bin/haproxy-lkl.sh
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/kuoruan/shell-scripts/master/ovz-bbr/bin/haproxy-lkl.sh [following]
--2019-03-23 02:20:53--  https://raw.githubusercontent.com/kuoruan/shell-scripts/master/ovz-bbr/bin/haproxy-lkl.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7517 (7.3K) [text/plain]
Saving to: '/usr/local/haproxy-lkl/sbin/haproxy-lkl'

/usr/local/haproxy-lk 100%[=========================>]   7.34K  --.-KB/s    in 0s      

2019-03-23 02:20:53 (61.8 MB/s) - '/usr/local/haproxy-lkl/sbin/haproxy-lkl' saved [7517/7517]

+ wget -O /lib/systemd/system/haproxy-lkl.service --no-check-certificate https://github.com/kuoruan/shell-scripts/raw/master/ovz-bbr/startup/haproxy-lkl.systemd
--2019-03-23 02:20:53--  https://github.com/kuoruan/shell-scripts/raw/master/ovz-bbr/startup/haproxy-lkl.systemd
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/kuoruan/shell-scripts/master/ovz-bbr/startup/haproxy-lkl.systemd [following]
--2019-03-23 02:20:53--  https://raw.githubusercontent.com/kuoruan/shell-scripts/master/ovz-bbr/startup/haproxy-lkl.systemd
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 399 [text/plain]
Saving to: '/lib/systemd/system/haproxy-lkl.service'

/lib/systemd/system/h 100%[=========================>]     399  --.-KB/s    in 0s      

2019-03-23 02:20:53 (47.8 MB/s) - '/lib/systemd/system/haproxy-lkl.service' saved [399/399]

+ wget -O /usr/local/haproxy-lkl/lib64/liblkl-hijack.so --no-check-certificate https://github.com/kuoruan/shell-scripts/raw/master/ovz-bbr/lib64/liblkl-hijack.so-20170724
--2019-03-23 02:20:53--  https://github.com/kuoruan/shell-scripts/raw/master/ovz-bbr/lib64/liblkl-hijack.so-20170724
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/kuoruan/shell-scripts/master/ovz-bbr/lib64/liblkl-hijack.so-20170724 [following]
--2019-03-23 02:20:54--  https://raw.githubusercontent.com/kuoruan/shell-scripts/master/ovz-bbr/lib64/liblkl-hijack.so-20170724
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6630177 (6.3M) [application/octet-stream]
Saving to: '/usr/local/haproxy-lkl/lib64/liblkl-hijack.so'

/usr/local/haproxy-lk 100%[=========================>]   6.32M  --.-KB/s    in 0.1s    

2019-03-23 02:20:54 (66.1 MB/s) - '/usr/local/haproxy-lkl/lib64/liblkl-hijack.so' saved [6630177/6630177]

+ md5sum -c
+ echo b50fc6a7ccfc70c76f44506814e7e18b  /usr/local/haproxy-lkl/lib64/liblkl-hijack.so
/usr/local/haproxy-lkl/lib64/liblkl-hijack.so: OK
+ sleep 3
+ systemctl start haproxy-lkl
+ sleep 3
+ timeout 2 bash -c </dev/tcp/10.0.0.2/23456
+ systemctl disable haproxy-lkl.service
+ rm -f /lib/systemd/system/haproxy-lkl.service
+ /usr/local/haproxy-lkl/sbin/haproxy-lkl -c
+ rm -rf /usr/local/haproxy-lkl
很遗憾，服务启动失败。
你可以查看上面的日志来获取原因，
或者，你可以到我们的群里反馈一下。

**Comment by kuoruan** [comment]
很多 OpenVZ 的机器都会启动失败，说不出什么原因，你只有尝试其他方式启用了
