### ISSUE TITLE
服务端无法安装Centos 6 x86 bbr

### ISSUE THREAD

**Issue by jim131** [kuoruan/shell-scripts#37]
用的是搬瓦工自带的root shell，按照命令行安装时，一直报下载失败，要我手动下载这个
https://github.com/kuoruan/shell-scripts/raw/master/kcptun/bin/jq-linux32
但是上面这个链接已不存在。

我再次尝试把kcptun.sh这个文件保存在/usr/local/kcptun/bin这个目录底下 但是依旧无法运行
以下为报错信息：

[root /]# wget --no-check-certificate https://github.com/kuoruan/shell-scripts/raw/master/kcptun/kcptun.sh
--2019-04-08 13:03:34--  https://github.com/kuoruan/shell-scripts/raw/master/kcptun/kcptun.sh
Resolving github.com... 192.30.255.113, 192.30.255.112
Connecting to github.com|192.30.255.113|:443... connected.HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/kuoruan/shell-scripts/master/kcptun/kcptun.sh [following]
--2019-04-08 13:03:35--  https://raw.githubusercontent.com/kuoruan/shell-scripts/master/kcptun/kcptun.sh
Resolving raw.githubusercontent.com... 151.101.196.133
Connecting to raw.githubusercontent.com|151.101.196.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 66753 (65K) [text/plain]
Saving to: “kcptun.sh.11”

     0K .......... .......... .......... .......... .......... 76% 43.3M 0s
    50K .......... .....                                      100%  227M=0.001s

2019-04-08 13:03:35 (53.4 MB/s) - “kcptun.sh.11” saved [66753/66753]

[root /]# sh kcptun.sh
[H[J#########################################################
# Kcptun 服务端一键安装脚本                             #
# 该脚本支持 Kcptun 服务端的安装、更新、卸载及配置      #
# 脚本作者: Index <kuoruan@gmail.com>                   #
# 作者博客: https://blog.kuoruan.com/                   #
# Github: https://github.com/kuoruan/shell-scripts      #
# QQ交流群: 43391448, 68133628                          #
#           633945405                                   #
#########################################################
请输入 Kcptun 服务端运行端口 [1~65535]
这个端口就是 Kcptun 客户端连接的端口
---------------------------
端口 = 29900
---------------------------
请输入需要加速的地址
可以输入主机名称、IPv4 地址或者 IPv6 地址
---------------------------
加速地址 = 127.0.0.1
---------------------------
请输入需要加速的端口 [1~65535]
---------------------------
加速端口 = 12984
---------------------------
请设置 Kcptun 密码(key)
该参数必须两端一致
---------------------------
密码 = very fast
---------------------------
请选择加密方式(crypt)
强加密对 CPU 要求较高，
如果是在路由器上配置客户端，
请尽量选择弱加密或者不加密。
该参数必须两端一致
(1) aes
(2) aes-128
(3) aes-192
(4) salsa20
(5) blowfish
(6) twofish
(7) cast5
(8) 3des
(9) tea
(10) xtea
(11) xor
(12) none
-----------------------------
加密方式 = aes
-----------------------------
请选择加速模式(mode)
加速模式和发送窗口大小共同决定了流量的损耗大小
如果加速模式选择“手动(manual)”，
将进入手动档隐藏参数的设置。
(1) normal
(2) fast
(3) fast2
(4) fast3
(5) manual
---------------------------
加速模式 = fast
---------------------------
请设置 UDP 数据包的 MTU (最大传输单元)值
---------------------------
MTU = 1350
---------------------------
请设置发送窗口大小(sndwnd)
发送窗口过大会浪费过多流量
---------------------------
sndwnd = 512
---------------------------
请设置接收窗口大小(rcvwnd)
---------------------------
rcvwnd = 512
---------------------------
请设置前向纠错 datashard
该参数必须两端一致---------------------------
datashard = 10
---------------------------
请设置前向纠错 parityshard
该参数必须两端一致
---------------------------
parityshard = 3
---------------------------
请设置差分服务代码点(DSCP)
---------------------------
DSCP = 0
---------------------------
是否关闭数据压缩?
---------------------------
nocomp = false
---------------------------
是否屏蔽 open/close 日志输出?
---------------------------
quiet = false
---------------------------
是否记录 SNMP 日志?
---------------------------
不记录 SNMP 日志
---------------------------
是否开启 pprof 性能监控?
地址: http://IP:6060/debug/pprof/
---------------------------
pprof = false
---------------------------
基础参数设置完成，是否设置额外的隐藏参数?
通常情况下保持默认即可，不用额外设置
---------------------------
不配置隐藏参数
---------------------------
配置完成。
请按任意键继续或 Ctrl + C 退出
stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device+ wget -O /usr/local/kcptun/bin/jq --no-check-certificate https://github.com/kuoruan/shell-scripts/raw/master/kcptun/bin/jq-linux32
--2019-04-08 13:04:00--  https://github.com/kuoruan/shell-scripts/raw/master/kcptun/bin/jq-linux32
Resolving github.com... 192.30.255.113, 192.30.255.112
Connecting to github.com|192.30.255.113|:443... connected.HTTP request sent, awaiting response... 404 Not Found
2019-04-08 13:04:01 ERROR 404: Not Found.

+ wget -O /usr/local/kcptun/bin/jq --no-check-certificate https://github.com/kuoruan/shell-scripts/raw/master/kcptun/bin/jq-linux32
--2019-04-08 13:04:01--  https://github.com/kuoruan/shell-scripts/raw/master/kcptun/bin/jq-linux32
Resolving github.com... 192.30.255.113, 192.30.255.112
Connecting to github.com|192.30.255.113|:443... connected.HTTP request sent, awaiting response... 404 Not Found
2019-04-08 13:04:01 ERROR 404: Not Found.

+ wget -O /usr/local/kcptun/bin/jq --no-check-certificate https://github.com/kuoruan/shell-scripts/raw/master/kcptun/bin/jq-linux32
--2019-04-08 13:04:01--  https://github.com/kuoruan/shell-scripts/raw/master/kcptun/bin/jq-linux32
Resolving github.com... 192.30.255.112, 192.30.255.113
Connecting to github.com|192.30.255.112|:443... connected.HTTP request sent, awaiting response... 404 Not Found
2019-04-08 13:04:02 ERROR 404: Not Found.

文件下载或校验失败! 请重试。
URL: https://github.com/kuoruan/shell-scripts/raw/master/kcptun/bin/jq-linux32
如果下载多次失败，你可以手动下载文件:
1. 下载文件 https://github.com/kuoruan/shell-scripts/raw/master/kcptun/bin/jq-linux32
2. 将文件重命名为 jq
3. 上传文件至目录 /usr/local/kcptun/bin
4. 重新运行安装脚本

注: 文件目录 . 表示当前目录，.. 表示当前目录的上级目录

Exit code: 1

**Comment by kuoruan** [comment]
把当前目录下所有的 kcptun.sh 文件删除

rm -f kcptun.sh*

然后重新下载脚本安装

jim131 <notifications@github.com> 于2019年4月9日周二 上午1:18写道：
