### ISSUE TITLE
kcptun是否可以用systemd来管理？

### ISSUE THREAD

**Issue by ChenWenBrian** [kuoruan/shell-scripts#38]
centos环境，已经有systemd了，而且之前装其他服务也有supervisor的配置了。不知道一键脚本里是否可以添加redhat linux环境直接使用systemd管理服务的启动？

**Comment by kuoruan** [comment]
脚本为了支持多服务端启动引入的 supervisor，systemd 用于启动 supervisor，如果你已有以前的配置，可以先将以前的配置保存下来，用 kcptun.sh 安装完成之后，将配置文件拷贝到 ```/etc/supervisor/conf.d``` 里边

**Comment by ChenWenBrian** [comment]
好吧，其实我主要是想保持减少监管程序的实用，尽量系统有就直接用原生的，多谢回复
