### ISSUE TITLE
最新的部署脚本的配置完成后sndwnd和rcvwnd结果显示反了

### ISSUE THREAD

**Issue by ChenWenBrian** [kuoruan/shell-scripts#39]
我在centos 7.4上安装完成后，sndwnd配置的是256，rcvwnd是512，结果除了红色高亮部分显示的结果是对的，中间的json配置和手机配置部分的这两个值都是显示的都是反的。但是kcptun的实际json配置文件是正确的。该bug不影响使用，但是对新人还是会造成迷惑。

**Comment by kuoruan** [comment]
#9 #24

**Comment by kuoruan** [comment]
服务端和客户端相对，服务端发送，客户端接受。客户端发送，服务端接收。
所以 服务端 sndwnd -> 客户端 rcvwnd，客户端 sndwnd -> 服务端 rcvwnd

**Comment by ChenWenBrian** [comment]
解释的相当清晰，一直以来还以为都是以服务端的配置为准，thanks
