### ISSUE TITLE
启动 Supervisor 失败

### ISSUE THREAD

**Issue by iguoya** [kuoruan/shell-scripts#4]
2017-07-15 21:18:09 (47.2 MB/s) - ‘/lib/systemd/system/supervisord.service’ saved [418/418]

+ systemctl daemon-reload
警告: 自动添加 iptables 规则失败
如有必要, 请手动添加端口 29900 的防火墙规则:
    iptables -I INPUT -p udp --dport 29900 -j ACCEPT
    service iptables save
    service iptables restart
+ sleep 3
Job for supervisord.service failed because the control process exited with error code. See "systemctl status supervisord.service" and "journalctl -xe" for details.
启动 Supervisor 失败, Kcptun 无法正常工作!
请反馈给脚本作者。

**Comment by kuoruan** [comment]
```
systemctl status supervisord.service
```

**Comment by JesseWo** [comment]
Systemd的单元描述文件分散在三个目录：
* /lib/systemd/system：系统默认的单元文件
* /etc/systemd/system：用户安装的软件的单元文件
* /usr/lib/systemd/system：用户自己定义的单元文件

而在此脚本中作者选择了 `/lib/systemd/system/` 目录来放 `supervisord.service`，所以我尝试了以下**解决方案：**
修改脚本， 将 `/lib/systemd/system/supervisord.service` 改为 `/etc/systemd/system/supervisord.service`, 
再运行就成功了。

**Comment by kuoruan** [comment]
@JesseWo 

针对你提到的这个问题，我查了一下资料，确实 ```/etc/systemd/system``` 目录要优于 ```/lib/systemd/system```，当时写脚本时没在意放置位置，没想到还会引起无法启动的问题？

https://www.digitalocean.com/community/tutorials/understanding-systemd-units-and-unit-files

The files that define how ```systemd``` will handle a unit can be found in many different locations, each of which have different priorities and implications.

The system's copy of unit files are generally kept in the ```/lib/systemd/system``` directory. When software installs unit files on the system, this is the location where they are placed by default.

Unit files stored here are able to be started and stopped on-demand during a session. This will be the generic, vanilla unit file, often written by the upstream project's maintainers that should work on any system that deploys ```systemd``` in its standard implementation. You should not edit files in this directory. Instead you should override the file, if necessary, using another unit file location which will supersede the file in this location.

If you wish to modify the way that a unit functions, the best location to do so is within the ```/etc/systemd/system``` directory. Unit files found in this directory location take precedence over any of the other locations on the filesystem. If you need to modify the system's copy of a unit file, putting a replacement in this directory is the safest and most flexible way to do this.

If you wish to override only specific directives from the system's unit file, you can actually provide unit file snippets within a subdirectory. These will append or modify the directives of the system's copy, allowing you to specify only the options you want to change.

The correct way to do this is to create a directory named after the unit file with ```.d``` appended on the end. So for a unit called ```example.service```, a subdirectory called ```example.service.d``` could be created. Within this directory a file ending with ```.conf``` can be used to override or extend the attributes of the system's unit file.

There is also a location for run-time unit definitions at ```/run/systemd/system```. Unit files found in this directory have a priority landing between those in ```/etc/systemd/system``` and ```/lib/systemd/system```. Files in this location are given less weight than the former location, but more weight than the latter.

The ```systemd``` process itself uses this location for dynamically created unit files created at runtime. This directory can be used to change the system's unit behavior for the duration of the session. All changes made in this directory will be lost when the server is rebooted.

**Comment by ThinkingXuan** [comment]
那个改脚本的方法具体怎么操作，能告诉一下吗？

**Comment by ThinkingXuan** [comment]
> Systemd
怎么修改
