### ISSUE TITLE
kcptun版本更新后，该脚本似乎出了问题

### ISSUE THREAD

**Issue by dyingway** [kuoruan/shell-scripts#40]
服务器端LOG一直提示broken pipe。

原来在VPS上按照脚本安装成功了。然后更新出错，随后利用备份还原更新前的状态后可以继续使用。

然后使用其他新的vps，全新安装，LOG依然broken pipe（最新版的KCPTUN29190418）

服务器分别是DEBIAN和UBUNTU。

**Comment by kuoruan** [comment]
https://github.com/xtaci/kcptun/releases/tag/v20190418

按官方的说法是 20190418 已经修复了问题，你的客户端是否已经更新了？

**Comment by dyingway** [comment]
感谢回复。更新到了kcptun-windows-amd64-20190418.tar.gz。

**Comment by DeanJing** [comment]
一些文件下载失败！安装脚本需要能访问到 github.com，请检查服务器网络。
注意: 一些国内服务器可能无法正常访问 github.com。
可以ping通github的，这个原因怎么解决

**Comment by kuoruan** [comment]
@DeanJing 
```wget https://github.com/xtaci/kcptun/releases/download/v20190428/kcptun-darwin-amd64-20190428.tar.gz```
试试可以吗？
一般来说， Github 的下载地址在国内是被墙的
