### ISSUE TITLE
一键安装过程中有条说明错了

### ISSUE THREAD

**Issue by zhoubin155** [kuoruan/shell-scripts#41]
是否开启pprof性能监控   默认是false (开启 )       选N后是开启  选Y才是关闭
应该是 是否关闭pprof性能监控 才对吧

**Comment by kuoruan** [comment]
看了一下源码，当 pprof 为 true 时表示开启，并没有问题
https://github.com/xtaci/kcptun/blob/ec9ace1de0/server/main.go#L364
