### ISSUE TITLE
Red Hat默认是python2,而不是python

### ISSUE THREAD

**Issue by niaiai** [kuoruan/shell-scripts#42]
我这使用Red Hat Enterprise Linux release 8.0 (Ootpa)的过程中发现,系统自带的python和pip命令是python2/pip2,脚本找不到python/pip命令而退出执行.

**Comment by kuoruan** [comment]
由于系统过多，而且都不统一，可能会出现 pip，pip2，pip3 等。无法对单个系统进行修改。
你可以做一个软链接 pip -> pip2

**Comment by niaiai** [comment]
我就是做了软连接才安装成功的
