### ISSUE TITLE
启动supervisor失败了

### ISSUE THREAD

**Issue by liuzheng36** [kuoruan/shell-scripts#44]
2019-07-01 15:22:08 (14.8 MB/s) - “/etc/init.d/supervisord” saved [2107/2107]

+ chmod a+x /etc/init.d/supervisord
iptables: Saving firewall rules to /etc/sysconfig/iptables:[  OK  ]
iptables: Setting chains to policy ACCEPT: filter          [  OK  ]
iptables: Flushing firewall rules:                         [  OK  ]
iptables: Unloading modules:                               [  OK  ]
iptables: Applying firewall rules:                         [  OK  ]
+ sleep 3
Starting supervisord: Error: File contains no section headers.
file: '/etc/supervisor/supervisord.conf', line: 1
'Traceback (most recent call last):\n'
For help, use /usr/local/bin/supervisord -h
                                                           [FAILED]
启动 Supervisor 失败, Kcptun 无法正常工作!
请反馈给脚本作者。

啊，比较小白=.=第一次弄这个东西，然后supervisor这里总是出错，看到之前有相关的问题但貌似并不一样。

**Comment by kuoruan** [comment]
```
cat /etc/supervisor/supervisord.conf
```
输出的内容发上来看看

**Comment by liuzheng36** [comment]
> ```
> cat /etc/supervisor/supervisord.conf
> ```
> 
> 输出的内容发上来看看


Traceback (most recent call last):
  File "/usr/bin/echo_supervisord_conf", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: meld3>=0.6.5
[include]
files = /etc/supervisor/conf.d/*.conf

结果是这样的。

**Comment by kuoruan** [comment]
```
rm -f /etc/supervisor/supervisord.conf
rm -f kcptun.sh*
wget --no-check-certificate https://github.com/kuoruan/shell-scripts/raw/master/kcptun/kcptun.sh
sh kcptun.sh
```

**Comment by liuzheng36** [comment]
> ```
> rm -f /etc/supervisor/supervisord.conf
> rm -f kcptun.sh*
> wget --no-check-certificate https://github.com/kuoruan/shell-scripts/raw/master/kcptun/kcptun.sh
> sh kcptun.sh
> ```

OK，已解决，谢谢大佬！
