### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by owenli25** [kuoruan/shell-scripts#45]
kcptun.sh: 1015: local: file.: bad variable name
安装出错，不知道怎么解决
系统用的Debian9

**Comment by kuoruan** [comment]
```
rm -f kcptun.sh*
wget --no-check-certificate https://github.com/kuoruan/shell-scripts/raw/master/kcptun/kcptun.sh
sh kcptun.sh
```

**Comment by owenli25** [comment]
> ```
> rm -f kcptun.sh*
> wget --no-check-certificate https://github.com/kuoruan/shell-scripts/raw/master/kcptun/kcptun.sh
> sh kcptun.sh
> ```

还是一样的问题

**Comment by kuoruan** [comment]
已修复 af4ee0c8c4c8e776827b6186682ba92ea78102da
重新下载脚本安装
