### ISSUE TITLE
最新版本，安装以后。启动成功。但是发现端口并没有被监听。

### ISSUE THREAD

**Issue by heyunxu** [kuoruan/shell-scripts#46]
安装成功以后，查看状态是绿色的active，我监听的是：29900端口，但是我使用：netstat -ano | grep 29900，发现并没有发现程序监听这个端口。

**Comment by kuoruan** [comment]
kcptun 的进程是否运行？
```
ps -ef | grep kcptun
```
然后再看看 kcptun 的配置文件
```
cat /usr/local/kcptun/server-config.json
```

**Comment by pengneal** [comment]
遇到一样的问题，不管执行任何操作，并且一直提示  实例配置文件存在错误, 请检查!

**Comment by pengneal** [comment]
进程没有运行。

**Comment by kuoruan** [comment]
重新下载脚本，然后把原实例删了，重新添加一个试试。

**Comment by aishlai** [comment]
我也发现了，我的是症状是，也是不监听接口
