### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by liaoran** [kuoruan/shell-scripts#5]
你好：
我在alpharacks上安装，报错：
+ ip tuntap del dev lkl-tap-test mode tap
+ ip tuntap add dev lkl-tap-test mode tap
open: No such file or directory
我开启了PPP和TUN/TAP，难道是因为alpharacks禁用了NAT，但是我开启了/etc/sysctl.conf，
cat /proc/sys/net/ipv4/ip_forward是1
请问是什么情况

**Comment by kuoruan** [comment]
我这里没有 alpharacks 的机器，所以无法给意见。
但是我遇到过一些 vps 无法创建 tun/tap 的情况
你试试用 rinetd 的方式吧

**Comment by kuoruan** [comment]
https://gist.github.com/codexss/1d5a834c479bb1532b9f82b23ee2f3fa
