### ISSUE TITLE
使用一键安装BBR脚本后ss不可用

### ISSUE THREAD

**Issue by f43110** [kuoruan/shell-scripts#6]
安装过程没有任何问题，然而之后测试发现ss不可用
环境是 Ubuntu 16.04 x64    Linux 2.6.32-042stab123.3

**Comment by kuoruan** [comment]
关闭 firewalld

**Comment by f43110** [comment]
试过，但是依然没用

**Comment by kuoruan** [comment]
先看看 10.0.0.2 能不能通，再看看 iptables，实在不行的话，只有卸载了

**Comment by f43110** [comment]
可以ping通，iptables也没有问题
在博客的评论区找到了类似情况，把shadowsocks的配置文件中的server改成0.0.0.0后解决了问题
谢谢博主！
