### ISSUE TITLE
使用lkl安装bbr之后，shadowsocks无法上网

### ISSUE THREAD

**Issue by richars** [kuoruan/shell-scripts#7]
不开bbr，ss没问题，但开了bbr之后，就无法上网。
openvz的bandwagon，求教。

**Comment by kuoruan** [comment]
什么系统，不行的话只有卸载

**Comment by richars** [comment]
ubuntu , openyz, python版的shadowsocks

**Comment by kuoruan** [comment]
你看我博客，用 rinetd-bbr 吧
