### ISSUE TITLE
磁盘空间被占满，另外，占用了127.0.0.1，请问怎样删除该服务？

### ISSUE THREAD

**Issue by xiasummer** [kuoruan/shell-scripts#8]
相关问题描述放在这里了

https://github.com/xtaci/kcptun/issues/488

求发布者给个删除本服务的方法。

**Comment by xiasummer** [comment]
另外，这里提到的服务中，为什么会在 /var/discourse/backup中输出如此多的压缩包呢？

**Comment by kuoruan** [comment]
```
./kcptun.sh uninstall
```
脚本里边没有任何代码用于输出内容到 ```/var/discourse/backup```
猜测是 vps 服务商的数据备份
